### ISSUE TITLE
Valid UUID not parsing correctly

### ISSUE THREAD

**Issue by owentran** [nu7hatch/gouuid#26]
The following UUID has passed several other validations but fails with the gouuid library?

```
package main

import (
    "fmt"

    "github.com/nu7hatch/gouuid"
)

func main() {
    s := "1c08d1b4-3cd4-698d-e053-0100007f2bc1"
    if _, err := uuid.ParseHex(s); err != nil {
        fmt.Printf("Cannot Parse %+v", err)
    }
}
```

**Comment by owentran** [comment]
Had to switch libraries, moved to: github.com/satori/go.uuid until this issue can be resolved.

**Comment by jaytaylor** [comment]
@owentran The satori package is much much better..

For more info see the deprecation msg in my fork: https://github.com/jaytaylor/uuid

**Comment by owentran** [comment]
Yup, we switched on over. Thanks for the note and for your earlier
contributions. -o

**Comment by tpiron** [comment]
The first character of the third block has to be a number between 1 and 5 https://github.com/nu7hatch/gouuid/blob/master/uuid.go#L40, I had the same issue, I'll change my code to use satori/go.uuid .
